spring.application.name=bom-project

#spring.datasource.url=jdbc:postgresql://localhost:5432/bomdb
#spring.datasource.username=postgres
#spring.datasource.password=1234
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.autoconfigure.exclude=\
org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration,\
org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration

jwt.secret=${JWT_SECRET}
jwt.access-token-ttl=${JWT_ACCESS_TOKEN_TTL:3600}